name: C# build and test
on: 
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'

jobs:
  test-Windows:  
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.7.0
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
        
      - name: Lint
        run: $files = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $files) {dotnet format $file.FullName}
        
      - name: Build Solutions
        run: $files = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $files) {dotnet build $file.FullName}
        
      - name: Run Tests
        run: $files = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $files) {dotnet test $file.FullName}
  
  test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      - name: Lint
        run: for file in $(find . -name "*.sln"); do dotnet format $file; done
        
      - name: Build Solutions
        run: for file in $(find . -name "*.sln"); do dotnet build $file; done
        
      - name: Run Tests
        run: for file in $(find . -name "*.sln"); do dotnet test $file; done
